### ISSUE TITLE
Missing Options for Import Solutions

### ISSUE THREAD

**Issue by smgtreker** [MicrosoftDocs/power-platform#269] opened 2020-06-16 11:36 UTC
The import solutions section needs additional information added; e.g. "Import as a Holding Solution"; how to subsequently apply the solution upgrade using the build tools. "Import as a Managed Solution"; what are the implications of this? E.g. Can you export an unmanaged solution and then import it as a managed solution?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2022-08-13 00:12
@smgtreker  Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-08-13 00:12 UTC
Labels: alm, open-for-too-long, assigned-to-author, powerapps/svc, Pri2
