### ISSUE TITLE
Share button not present on team site's Home page

### ISSUE THREAD

**Issue by CalvinQuark** [MicrosoftDocs/power-platform#1559] opened 2022-10-29 14:57 UTC
When I attempt to follow these directions, I am not seeing a "Share" option on my team site's Home page. The only menu bar options across the top are New, Page Details, Analytics, and Edit. So, it's not clear to how to follow this article because of the discrepancy between what I'm encountering versus what this article depicts. Perhaps there is a way to enhance this article to inform the uninitiated of the root cause for the missing Share button and how to address it. I'm a global admin btw.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 60b6702c-b45c-9c90-f809-fe0d276ab526
* Version Independent ID: fc9e44c1-fa3e-93c4-f574-ae2cd6c3ffdc
* Content: [Set up customer engagement apps to use SharePoint Online - Power Platform](https://learn.microsoft.com/en-us/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online)
* Content Source: [power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/set-up-dynamics-365-online-to-use-sharepoint-online.md)
* Service: **power-platform**
* Sub-service: **admin**
* GitHub Login: @Mattp123
* Microsoft Alias: **matp**

**Comment by bishalgoswami** [comment] 2022-10-29 15:00
Thanks for your comment, @CalvinQuark. This issue has been assigned to the doc author for review.

**Comment by Mattp123** [comment] 2023-01-13 19:42
@CalvinQuark - I can't reproduce your issue. When I follow the steps a Share button is displayed (although the UI has changed).
![image](https://user-images.githubusercontent.com/21203819/212405150-8d3278f6-8a81-4f6e-b461-27e3788645e5.png)

You can contact Support, here: https://powerapps.microsoft.com/support/ 

Closing this issue.

**Closed by Mattp123** 2023-01-13 19:42 UTC
Labels: assigned-to-author
