### ISSUE TITLE
Documentation for "user running a flow" missing

### ISSUE THREAD

**Issue by nicksaahs** [MicrosoftDocs/power-platform#507] opened 2020-12-08 12:46 UTC
In the section [Do users who run...](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#do-users-who-run-flows-need-to-be-licensed-or-do-only-users-who-create-flows-need-to-be-licensed), a lot more clarification is needed. Please include scenario's such as:

- scheduled flows (who "runs" those)
- flows started from an http-request
- ...
"There are features" and "Normally" are not documentation, they are avoidance thereof.
It should be quite possible for you guys to document each type of trigger and the matching licensing behaviour.
Also note that some of this probably ties in closely with the concept of a flow "owner"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#do-users-who-run-flows-need-to-be-licensed-or-do-only-users-who-create-flows-need-to-be-licensed)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by KendalBond007** [comment] 2023-08-01 18:29
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by KendalBond007** 2023-08-01 18:29 UTC
Labels: power-platform/svc, Pri2, reviewed-KendalBond007
