### ISSUE TITLE
Errors in referenced PowerShell script

### ISSUE THREAD

**Issue by dialedin2014** [MicrosoftDocs/power-platform#519] opened 2020-12-15 18:51 UTC
When running the script to set up the Service Principal, errors occur.  There appears to have been breaking changes to the commandlets it calls.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tools.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment] 2023-04-10 22:15
@dialedin2014 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue

**Closed by Mattp123** 2023-04-10 22:15 UTC
Labels: alm, open-for-too-long, assigned-to-author, powerapps/svc, Pri2
