### ISSUE TITLE
ALM and Tenants

### ISSUE THREAD

**Issue by donalmc** [MicrosoftDocs/power-platform#565] opened 2021-01-27 11:19 UTC
Hi - the ALM Basics page is good but I think it should include some information about O365 tenants.
Ideally, Power Platform devs need access to O365 admin, so as to be able to add dummy users, swap licenses etc. - which of course is unlikely to happen in the real world.
So in reality, ALM should start with a dev tenant, external to the organization the dev work for.
What is the advice around this?
The O365 Developer program gives you a tenant but this does not come with any Dataverse capacity - if it did, this would solve the issue,
Do you have any advice on how to include tenants into ALM?
Thanks,
Donal

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: edc6c5a2-f29f-12bd-c619-a1b8503517c5
* Version Independent ID: 773f57ee-ff34-04d0-43d9-6cc268e6a8c1
* Content: [Application lifecycle management (ALM) basics with Microsoft Power Platform - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/basics-alm)
* Content Source: [power-platform/alm/basics-alm.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/basics-alm.md)
* Service: **powerapps**
* GitHub Login: @shmcarth
* Microsoft Alias: **shmcarth**

**Comment by Mattp123** [comment] 2023-04-10 22:17
@donalmc - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2023-04-10 22:17 UTC
Labels: alm, open-for-too-long, powerapps/svc, Pri2
