### ISSUE TITLE
Difficult to understand background operation toggle

### ISSUE THREAD

**Issue by DavidPezzoli** [MicrosoftDocs/power-platform#517] opened 2020-12-11 15:29 UTC
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c9f9a37-0f20-6201-eabe-9420c008814a
* Version Independent ID: 64ae24fc-ae91-759e-0f97-2daa809d59a4
* Content: [Administration mode - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/admin-mode)
* Content Source: [power-platform/admin/admin-mode.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/admin-mode.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

The definition "Background operations" make me some confusion, I have difficult to understand this definition:
![image](https://user-images.githubusercontent.com/45006314/101919826-537c7f80-3bcb-11eb-8bd1-cb557ba2c76f.png)

Every time I need to keep on async operations I don't understand what really happen if I click on or not on the toggle. For me it isn't clear your definition. Please add one / two simply images in order to explain well what the toggle do. Here my example suggestion:

- To Enable Async Opertaion: 
![image](https://user-images.githubusercontent.com/45006314/101920514-31cfc800-3bcc-11eb-8d1f-7f11af81f3f6.png)

- To Disable Async Operation:
![image](https://user-images.githubusercontent.com/45006314/101921755-a3f4dc80-3bcd-11eb-9373-5ba15c27d1b9.png)

Thanks!

**Comment by KendalBond007** [comment] 2023-08-01 18:33
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by KendalBond007** 2023-08-01 18:33 UTC
Labels: power-platform/svc, Pri2, reviewed-KendalBond007
