### ISSUE TITLE
Link to: : Microsoft Power Platform Build Tools for Azure DevOps overview is not working

### ISSUE THREAD

**Issue by ClausKramer** [MicrosoftDocs/power-platform#1238] opened 2022-05-07 08:29 UTC
In this article the link to Azure DevOps overview is not working
https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/tools-apps-used-alm.md

**Comment by JimDaly** [comment] 2022-05-07 18:41
@ClausKramer 
Thanks for your feedback.
Generally, it helps if you use the **Feedback**  button in the topic. That will automatically include a link to the topic and the appropriate person will be assigned to address it.

The markdown file you linked to is the source for this page: [Overview of tools and apps used with ALM](https://docs.microsoft.com/en-us/power-platform/alm/tools-apps-used-alm), so assigning @Mattp123 

Within that page there is a link to [Microsoft Power Platform Build Tools for Azure DevOps overview](/powerapps/developer/common-data-service/build-tools-overview). 

The markdown file for this page doesn't exist anymore, but our re-direct system will take the reader to the new location for the topic: [Microsoft Power Platform Build Tools for Azure DevOps](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)

While the link could be updated to point to new location without depending on the redirect system, it is working as designed.
Unless you were referring to some other link on this page?

**Comment by Mattp123** [comment] 2023-01-13 19:27
@ClausKramer - I can't reproduce the link as broken. It directs to the article as expected. Reopen this issue if further help is needed.
Closing issue.

**Closed by Mattp123** 2023-01-13 19:27 UTC
Labels: alm
