### ISSUE TITLE
Document Dataverse for Teams Governance solution gap for GCC, GCC High and DoD regions

### ISSUE THREAD

**Issue by rrwolfe** [MicrosoftDocs/power-platform#1339] opened 2022-07-06 14:24 UTC
GCC, GCC High and DoD regions do not currently have the ability to post Adaptive Cards to Teams via bot. Due to this limitation, the Dataverse for Teams Governance solution fails to post Adaptive Cards when executed. If the flows supporting this solution are enabled, Dataverse for Teams owners will never receive the notifications for business justification and any Dataverse for Teams environment older than 7 days will get deleted automatically. 

We should document/highlight that the flows included with this part of the solution should not be enabled in environments that are hosted in GCC, GCC High and DoD regions until this platform capability (posting Adaptive Cards to Team via bot) is available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d744c67a-948f-63df-0e61-bb76809e534a
* Version Independent ID: d744c67a-948f-63df-0e61-bb76809e534a
* Content: [Set up Dataverse for Teams environment management - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-teams-components)
* Content Source: [power-platform/guidance/coe/setup-teams-components.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-teams-components.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment] 2022-07-06 14:27
Duplicate of #1299 and will be addressed with the next release, which is awaiting docs team review before being merged.

**Closed by manuelap-msft** 2022-07-06 14:27 UTC
