### ISSUE TITLE
[error]FileStorageService is not enabled for this org

### ISSUE THREAD

**Issue by broline** [MicrosoftDocs/power-platform#375] opened 2020-09-01 22:07 UTC
With no changes made to my [solution export task](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools), I started getting the following error when exporting one of my solutions: `[error]FileStorageService is not enabled for this org.` It was working fine less than 24hrs ago. I reverted to using the Wael Hamze tools which exports without error. I am also able to manually export a solution with no error.

![91910826-5c2cf380-ec75-11ea-8c41-94256a01f87d](https://user-images.githubusercontent.com/5590696/91911413-a9f62b80-ec76-11ea-9214-8d9c6ed1d982.png)

Wanted to see if this was related to any recent changes. Let me know if you need more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tools.md)
* Service: **powerapps**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by malaker** [comment] 2020-09-02 11:50
for organizations where customer key(BYOK)  feature is enable file column cannot be created in entity

**Comment by jagibe** [comment] 2020-10-13 12:39
I'm experiencing the same issue

Connected Org Version: 9.1.0.23177

**Comment by Mattp123** [comment] 2023-04-10 22:14
@broline - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2023-04-10 22:14 UTC
Labels: alm, assigned-to-author, powerapps/svc, Pri2
