### ISSUE TITLE
Automate new environment creation with AppId/Secret

### ISSUE THREAD

**Issue by aronmek** [MicrosoftDocs/power-platform#286] opened 2020-06-22 21:25 UTC
[Enter feedback here]
I understood from the documentation that if I want to use a Azure App Id with a Service secret (due to MFA limitations) then I would need to add that application into the target CDS environment as an application user.
If that's the case, is there a way to automate the creation of a new environment using the above approach? As far as I understand, In order to add the Application User that would still require an actual user to log in.

Can this somehow be setup with a multi phased pipeline requiring the user to give consent to create the application user?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tools.md)
* Service: **powerapps**
* GitHub Login: @phecke
* Microsoft Alias: **pehecke**

**Comment by phecke** [comment] 2022-08-13 00:14
@aronmek  Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by phecke** 2022-08-13 00:14 UTC
Labels: alm, open-for-too-long, assigned-to-author, powerapps/svc, Pri2
