### ISSUE TITLE
Sync Flows activation

### ISSUE THREAD

**Issue by petepuu** [MicrosoftDocs/power-platform#488] opened 2020-11-26 21:01 UTC
Does this recommendation apply anymore? I installed 1.71.5 Core and Admin | Sync Template v2 Flow was turned on after import meaning that it started immediately after import automatically

...We will avoid issues by enabling the flows in an explicit order. We recommend you repeat this order on each upgrade as well.

Turn on: CLEANUP - Admin | Sync Template v2 (Check Deleted)
**Wait until it finishes before you turn on any other flows.**
Ensure the Sync Template flows are already turned on for the following object types:
Apps, Connectors, Custom Connectors, Flows, Model Driven Apps, PVA, RPA
Turn on Admin | Sync Template v2. When it completes, turn it back off.
This will cause the flows for the objects listed in step 3 to run. Wait until all of these complete.
Turn back on Admin | Sync Template v2.
Turn on the rest of the flows listed in the solution_

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9fe69498-a485-5379-97ff-53fbe029f11a
* Version Independent ID: 5b3f9705-9e49-1575-4ae7-0293d12b739c
* Content: [Set up core components - Power Platform](https://docs.microsoft.com/en-us/power-platform/guidance/coe/setup-core-components)
* Content Source: [power-platform/guidance/coe/setup-core-components.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/guidance/coe/setup-core-components.md)
* Service: **power-platform**
* GitHub Login: @manuelap-msft
* Microsoft Alias: **mapichle**

**Comment by manuelap-msft** [comment] 2020-11-30 16:27
Did you upgrade from a previous version, or was this a clean install on a new environment?

**Comment by petepuu** [comment] 2020-11-30 20:06
I think it was a clean installation to new environment but not 100% sure. Have been testing so many times with different version to different environments so need to check that one more time :)

**Comment by manuelap-msft** [comment] 2020-11-30 20:07
Thank you! I tested a clean install today and the flows were off, but during an upgrade - if the flows were on before - the upgrade does not turn them off, which is expected behaviour. Be great if you could confirm that is the behaviour you are seeing as well

**Comment by petepuu** [comment] 2020-12-01 08:13
Tried again to new Trial environment using 1.71.5 version and the main sync flow was enabled automatically after import.

**Comment by petepuu** [comment] 2020-12-01 10:12
Decided to still create new demo tenant and same happened again. This is the status of sync flows immediately after import and first open of core solution. Version 1.71.5 and admin email and power automate env variables defined in import

![image](https://user-images.githubusercontent.com/8307644/100726672-eb10ef80-33cd-11eb-9e37-3083c61a261d.png)

**Comment by manuelap-msft** [comment] 2020-12-01 10:13
Hello,

we have since released 1.71.7 - does the same happen with that version?

**Comment by petepuu** [comment] 2020-12-01 10:58
Didn't happen with 1.71.7, so might be just 1.71.5 version problem?

**Comment by manuelap-msft** [comment] 2020-12-01 10:59
Great, thanks for confirming! 1.71.7 is our latest published version so I'll close this issue.

**Closed by manuelap-msft** 2020-12-01 10:59 UTC
Labels: coe
