### ISSUE TITLE
Missing parameter details in section

### ISSUE THREAD

**Issue by ahmadpirani** [MicrosoftDocs/power-platform#1958] opened 2023-05-26 07:13 UTC
[Enter feedback here]
The parameters mentioned for XCreateSidePaneActionForEntity does not match the list below it. The one missing is Page Type.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 636c9143-3812-476a-6b47-b729286d2017
* Version Independent ID: 636c9143-3812-476a-6b47-b729286d2017
* Content: [XSendAppNotification and related functions in Power Apps - Power Platform](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-send-app-notification)
* Content Source: [power-platform/power-fx/reference/function-send-app-notification.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/power-fx/reference/function-send-app-notification.md)
* Service: **power-platform**
* Sub-service: **power-fx**
* GitHub Login: @jaredha
* Microsoft Alias: **jaredha**

**Comment by bishalgoswami** [comment] 2023-05-26 09:00
Thanks for your comment, @ahmadpirani. This issue has been assigned to the doc author for review.

**Comment by jaredha** [comment] 2023-05-26 21:23
I've submitted updates to fix this. Thanks for catching the error. The issue is that we removed the unnecessary page type parameter from the functions. I had updated the tables to remove them, but not the syntax statements. They are now removed.

**Closed by jaredha** 2023-05-26 21:23 UTC
Labels: assigned-to-author
