### ISSUE TITLE
The powershell script is outdated

### ISSUE THREAD

**Issue by dirkr1** [MicrosoftDocs/power-platform#407] opened 2020-09-30 07:15 UTC
The given powershell script to create the key vault uses the AzureRM library.

Currently the Azure AZ library is the version that is working - but the script is not updated.

To have a quick fix just add the line:
    Enable-AzureRmAlias -Scope Process
to the script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d51ad6f-b7a7-7abd-f1d1-1d7963dd3d49
* Version Independent ID: 4612ff88-8457-2f49-8222-4fd110fd72f6
* Content: [Replicate data to Azure SQL Database using Data Export Service - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/replicate-data-microsoft-azure-sql-database)
* Content Source: [power-platform/admin/replicate-data-microsoft-azure-sql-database.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/replicate-data-microsoft-azure-sql-database.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by sartoris** [comment] 2020-11-13 15:42
@dirkr1 - Quick fix works! thank you

**Comment by jimholtz** [comment] 2021-02-10 01:29
@dirkr1 
Sorry for the delayed response. Thanks for the feedback. Can you indicate where this should be added in the article?

**Comment by laneswenka** [comment] 2021-06-03 22:25
I am following up to see who owns this feature, as it falls outside of my current purview.

**Comment by jimholtz** [comment] 2021-06-18 00:01
@dirkr1 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by jimholtz** 2021-06-18 00:01 UTC
Labels: PowerShell, open-for-too-long, waiting on internal feedback
