### ISSUE TITLE
How to delete an Environment?

### ISSUE THREAD

**Issue by gdstuart** [MicrosoftDocs/power-platform#738] opened 2021-05-18 14:32 UTC
[Enter feedback here]
Delete does not appear as a menu item, so this article is not helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: adb92ca9-41dc-d1d0-90df-09e7159e47d7
* Version Independent ID: 6c2a02de-a8db-cafa-6d81-861a027c07f2
* Content: [Delete an environment in Power Platform admin center - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/delete-environment)
* Content Source: [power-platform/admin/delete-environment.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/admin/delete-environment.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jcoxdco** [comment] 2021-05-18 16:51
This is a duplicate of issue #715

**Comment by jimholtz** [comment] 2021-05-19 23:11
@gdstuart 
Delete is not an option for the default environment. If you don't see delete for other environments, please contact support: https://powerapps.microsoft.com/support/

**Closed by jimholtz** 2021-05-19 23:11 UTC
