### ISSUE TITLE
Links on the page are not working

### ISSUE THREAD

**Issue by gabrieljunckes** [MicrosoftDocs/power-platform#1536] opened 2022-10-20 21:58 UTC
Please, update the links below.

_For an example of configuration and data deployment configuration, go to the ALMAcceleratorSampleSolution [deployment settings](https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorSampleSolution/config/deploymentSettings.json) and [custom deployment settings](https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorSampleSolution/config/customDeploymentSettings.json)._

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 95bfb99a-cdf3-2d32-7c9c-b6517e4716d5
* Version Independent ID: 95bfb99a-cdf3-2d32-7c9c-b6517e4716d5
* Content: [Configuration and data deployment in pipelines - Power Platform](https://learn.microsoft.com/en-us/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-config)
* Content Source: [power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-config.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/guidance/coe/setup-almacceleratorpowerplatform-deployment-config.md)
* Service: **power-platform**
* Sub-service: **guidance**
* GitHub Login: @jenschristianschroder
* Microsoft Alias: **jeschro**

**Comment by bishalgoswami** [comment] 2022-10-20 23:00
Thanks for your comment, @gabrieljunckes. This issue has been assigned to the doc author for review.

**Comment by jenschristianschroder** [comment] 2022-12-09 09:45
Thank you for reporting this.

This will be fixed in the next update.

Until then the links to the mentioned files are
https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorSampleSolution/config/Prod/deploymentSettings.json
https://github.com/microsoft/coe-starter-kit/blob/main/ALMAcceleratorSampleSolution/config/Prod/customDeploymentSettings.json

(Duplicate of  #1619)

**Closed by jenschristianschroder** 2022-12-09 09:45 UTC
Labels: assigned-to-author
