### ISSUE TITLE
Can Power Automate be Disabled?

### ISSUE THREAD

**Issue by devlinl** [MicrosoftDocs/power-platform#280] opened 2020-06-18 19:52 UTC
In the section titled, "Enable or disable Power Automate in your organization" there is an instruction: "Under Display behavior, select Show Power Automate on forms and in the site map to enable or disable Power Automate."

This instruction, and the section title, lead the reader to believe that Power Automate can be enabled and disabled at will.

However, the actual setting is labeled, "Show Power Automate on forms and in the site map. You cannot disable Power Automate once it is enabled in your organization"

If the feature truly cannot be turned off, then the documentation should be updated to reflect that. If the setting label is wrong, the documentation should be updated with a note indicating that the label of the setting is misleading and can be ignored, until such time that the setting label can be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63017419-1a44-fb00-68c3-a1f09b624f7d
* Version Independent ID: 8df68bc2-e216-f967-8b95-e76173587799
* Content: [Enable Power Automate integration to automate processes - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/enable-embedded-flow-in-your-organization#enable-or-disable-flow-in-your-dynamics-365-for-customer-engagement-apps-organization?utm_source=dynamics_crm&utm_content=app_notification)
* Content Source: [power-platform/admin/enable-embedded-flow-in-your-organization.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/enable-embedded-flow-in-your-organization.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment] 2021-06-16 21:21
@devlinl 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by jimholtz** 2021-06-16 21:21 UTC
Labels: waiting on internal feedback
