### ISSUE TITLE
"Normally" should be clarified.

### ISSUE THREAD

**Issue by wnzn** [MicrosoftDocs/power-platform#477] opened 2020-11-19 07:34 UTC
**Do users who run flows need to be licensed, or do only users who create flows need to be licensed?**
    
Any end user running a flow will need to be licensed either by the per user or per Power Automate plans.

There are features in Power Automate that are not running a flow directly, such as responding to an approval request or advancing a stage in a business process. These features are built on the Dataverse. **Normally**, any use of these features requires either a standalone Power Automate per user plan, or, that the flow that creates these business process environments or approval requests to be licensed under the per flow plan.

Can you please clarify what is meant by "Normally" in this context? If a user has an M365 E3 license, is this enough?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2cad5bd-4ffa-3671-0364-95e5b6f65256
* Version Independent ID: 6d0cc055-b7be-02d7-3ba8-55e400ccd21b
* Content: [Power Apps and Power Automate licensing FAQs - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-flow-licensing-faq#dataverse)
* Content Source: [power-platform/admin/powerapps-flow-licensing-faq.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-flow-licensing-faq.md)
* Service: **power-platform**
* GitHub Login: @dileepsinghmicrosoft
* Microsoft Alias: **dileeps**

**Comment by wnzn** [comment] 2021-06-25 15:56
It's been a while. Question still stands.

**Comment by wnzn** [comment] 2022-06-22 14:23
**There's a premium flow that sends approval requests to a set of users and then waits for the users to approve or reject the request before it continues running. Do the approvers need a premium license?**
Every user benefiting from the flow needs a license. But, if the flow is a personal automation where only the owner is benefiting from the flow, users who respond to approval requests don't need a premium license.

Well there's the answer then? Yet, "Personal automation" and "owner benefiting" is just more vague wording. Are you now going after anyone who has build an approval flow for SharePoint documents? You know, the kind that was for free with the old SharePoint Designer workflows that were deprecated?

Mind you, I might as well continue talking to myself here as no-one seems to care.

**Comment by KendalBond007** [comment] 2023-08-01 18:25
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by KendalBond007** 2023-08-01 18:25 UTC
Labels: power-platform/svc, Pri2, reviewed-KendalBond007
