### ISSUE TITLE
Conversion error with JSON setting file

### ISSUE THREAD

**Issue by Aurelien-SamS** [MicrosoftDocs/power-platform#1153] opened 2022-03-08 11:59 UTC
Good evening everyone.
For the deployment I created an application from which we fill in the environment variables and I retrieve them from the sharepoint list via the PnP-PowerShell. I managed to convert my string to JSON and I stored it in a file (D:\a\r1\a\file.json) but when importing the solution I got this error

![Capture d’écran 2022-03-08 124036](https://user-images.githubusercontent.com/70952106/157231563-91350541-fb0f-416b-8f24-ca6cb100fd31.png)

Screenshot of the solution import task

![Capture d’écran 2022-03-08 124712](https://user-images.githubusercontent.com/70952106/157232456-dbbe04a2-48e5-415a-a965-5014562bcae7.png)

I really don't know where to start here. Does anyone have an idea or can tell me where I messed up? 🙏

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca1df5d8-ef79-c56d-3950-0617da9f976b
* Version Independent ID: ff132857-2fc9-57d0-df24-d42c054cbf1c
* Content: [Pre-populate connection references and environment variables for automated deployments using Power Platform Build Tools - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/conn-ref-env-variables-build-tools)
* Content Source: [power-platform/alm/conn-ref-env-variables-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/conn-ref-env-variables-build-tools.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @kkanakas
* Microsoft Alias: **kartikka**

**Comment by Mattp123** [comment] 2023-04-10 22:29
@Aurelien-SamS - “Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2023-04-10 22:29 UTC
Labels: alm, open-for-too-long, assigned-to-author
