### ISSUE TITLE
Installer code not working 

### ISSUE THREAD

**Issue by jorisaeles** [MicrosoftDocs/power-platform#1170] opened 2022-03-16 13:00 UTC
[Enter feedback here]
Tried copying the code to install the packages but the compiler didn't accept it. Imported it as a task from within Azure DevOps pipe and it does work but also gave me different code.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment] 2023-04-10 22:31
@jorisaeles - “Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2023-04-10 22:31 UTC
Labels: alm, open-for-too-long, assigned-to-author
