### ISSUE TITLE
Does "Get-AdminPowerApp" list down model driven Apps?

### ISSUE THREAD

**Issue by DiptiC-InsightRun** [MicrosoftDocs/power-platform#304] opened 2020-07-06 08:36 UTC
Hello,

I have noticed that "Get-AdminPowerApp" doesn't list out the model-driven apps, does this command only list out canvas apps?

Thanks and Regards,

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 02f1be79-2b3a-31da-7a7d-ace1eac5d1f1
* Version Independent ID: fa7c7450-15a6-edc8-5671-f45763267ca6
* Content: [PowerShell support (preview) - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/powerapps-powershell)
* Content Source: [power-platform/admin/powerapps-powershell.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/powerapps-powershell.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment] 2020-07-06 16:56
@dips23 
If user does not have permission for the app, it won’t be listed. Please make sure the user has permission.

**Comment by dips23** [comment] 2020-07-08 03:07
Thank you for the response, I have ran that command as "Global Admin" and I have created model driven apps, therefore I can see them in UI but not in "Get-AdminPowerApp" command result.

Is there anything that I might be missing?

Thanks and Regards,
Dipti

**Comment by JimDaly** [comment] 2023-06-19 16:13
@laneswenka 
Can you take a look at this please?

**Comment by JimDaly** [comment] 2023-08-01 18:12
@laneswenka 

This is my test that indicates that model-driven apps are not returned

```
PS C:\WINDOWS\system32> Get-AdminPowerApp "Customer Service Hub"
PS C:\WINDOWS\system32> Get-AdminPowerApp "Account App"
PS C:\WINDOWS\system32> Get-AdminPowerApp "Account Reader"


AppName                  : 3de27a63-7949-434a-89f6-686b3058d08b
DisplayName              : Account Reader
CreatedTime              : 2020-09-27T23:26:50.7215901Z
Owner                    : @{id=db8540da-f71f-4250-9b98-9d55d46259d9; displayName=Jim Daly; type=User; tenantId=effdd265-a4b3-4bbf-90df-2794e5f57515; userPrincipalName=jdaly@crmue.onmicrosoft.com}
LastModifiedTime         : 2023-02-10T22:52:26.2785971Z
EnvironmentName          : 6a9e6fca-3ab6-477b-9d1f-e803fb928f55
UnpublishedAppDefinition :
IsFeaturedApp            : False
IsHeroApp                : False
BypassConsent            : False
Internal                 : @{name=3de27a63-7949-434a-89f6-686b3058d08b; id=/providers/Microsoft.PowerApps/scopes/admin/environments/6a9e6fca-3ab6-477b-9d1f-e803fb928f55/apps/3de27a63-7949-434a-89f6-686b3058d08b;
                           type=Microsoft.PowerApps/scopes/admin/apps; tags=; properties=; appLocation=unitedstates; isAppComponentLibrary=False; appType=ClassicCanvasApp}

PS C:\WINDOWS\system32>
```

**Customer Service Hub** and **Account App** are both model-driven apps. They return no results.
**Account Reader** is a canvas app, and results are returned.

Need to know whether this is by design because it seems people expect all types of app to be returned.

**Comment by KendalBond007** [comment] 2023-08-04 15:47
Within the table, line items are labeled with specific app uses as follows:

![image](https://github.com/MicrosoftDocs/power-platform/assets/104027141/64ee3f4f-db6f-4eb8-830d-b8b021afad7c)

This sort of callout gives explicit reference to what kind of apps are addressed by what cmdlets. To avoid possible additional confusion and minimize content maintenance no changes will be made to the document at this time.

**Closed** 2023-08-04 15:48 UTC
Labels: waiting on internal feedback, reviewed-KendalBond007
