### ISSUE TITLE
What is the Roadmap for getting Teams Integration in D365 in GCC?

### ISSUE THREAD

**Issue by tmsquared** [MicrosoftDocs/power-platform#314] opened 2020-07-16 01:17 UTC
The page referenced says Teams is one of "The following generally available features are not currently available:"

Is there a roadmap for when it will be? Many Government (Federal/State/Local) agencies are turning to virtual engagements as offices have been closed and are slow to open, even then at a reduced capacity. Some of our customers are looking at other options because we can't provide the integration between Teams and Dynamics. Allowing a Citizen to schedule a meeting that is attached to a Case in D365 and allow the system to automatically incorporate Teams meeting information into that appointment/case should be seamless for the government customer! 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a33278f2-b63d-c61a-920e-7fe85c31dd71
* Version Independent ID: f2f2f47f-6c2c-e49a-daeb-6608e2f47c3a
* Content: [Dynamics 365 US Government - Feature availability - Power Platform](https://docs.microsoft.com/en-us/power-platform/admin/government-feature-availability)
* Content Source: [power-platform/admin/government-feature-availability.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/admin/government-feature-availability.md)
* Service: **power-platform**
* GitHub Login: @jimholtz
* Microsoft Alias: **jimholtz**

**Comment by jimholtz** [comment] 2021-06-16 21:22
@tmsquared 
Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by jimholtz** 2021-06-16 21:22 UTC
Labels: waiting on internal feedback
