### ISSUE TITLE
Out of box Power Platform Tool Installer is failing with No match was found for the specified search criteria and module name

### ISSUE THREAD

**Issue by ugreg** [MicrosoftDocs/power-platform#852] opened 2021-08-17 22:39 UTC
When running the **Power Platform Tool Installer** task from a classic pipeline we get this error.
```ps
##[error]No match was found for the specified search criteria and module name 'Microsoft.PowerApps.Administration.PowerShell'. Try Get-PSRepository to see all available registered module repositories.
```

We have this configuration in place and have not made any changes in the past months. Could this mean there is some platform issue with this particular out of box task for Classic Pipelines?

![image](https://user-images.githubusercontent.com/8151045/129809806-df68aaf1-961a-4daa-ac49-7b1bbdc3d64b.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fba2155b-98b3-64e0-29f5-79cf2b1a90f1
* Version Independent ID: d2b30089-7cf3-563a-eb38-d112793beb9b
* Content: [Microsoft Power Platform Build Tools for Azure DevOps - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools)
* Content Source: [power-platform/alm/devops-build-tools.md](https://github.com/MicrosoftDocs/power-platform/blob/main/power-platform/alm/devops-build-tools.md)
* Service: **power-platform**
* Sub-service: **alm**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by gregdegruy** [comment] 2021-08-17 22:50
Root cause seems to be with PowerShell Gallery being down today, global impact possibly or United States  only?

![image](https://user-images.githubusercontent.com/8151045/129810725-e4c25e5b-e6be-4437-8549-b6922183372b.png)

**Comment by KendalBond007** [comment] 2023-08-23 18:35
Thanks for your feedback. We are closing this issue because it has remained unaddressed over a year (last activity 1 Dec 21). If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by KendalBond007** 2023-08-23 18:35 UTC
Labels: assigned-to-author, power-platform/svc, alm/subsvc, Pri2
