### ISSUE TITLE
Power Platform Set Solution Variable Referencing Incorrect Build Variable

### ISSUE THREAD

**Issue by mwebster5589** [MicrosoftDocs/power-platform#658] opened 2021-03-19 19:52 UTC
For the Power Platform Set Solution Variable section, it mentions using the BuildId from the Pipeline options to set the version number to. Based on the context of what is written, I believe the BuildNumber is what should be referenced. In the Pipeline options, you have the ability to format the Build Number, but not the Build ID. Then you would reference the Build.BuildNumber variable in the Solution Version Number setting; not the Build.BuidId variable.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2d7f63d-dcde-f057-555a-3fffce0f229c
* Version Independent ID: e4bba5f7-ae53-260f-269b-c8ad002ef696
* Content: [Build tool tasks - Power Platform](https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tool-tasks#power-platform-set-solution-version)
* Content Source: [power-platform/alm/devops-build-tool-tasks.md](https://github.com/MicrosoftDocs/power-platform/blob/master/power-platform/alm/devops-build-tool-tasks.md)
* Service: **power-platform**
* GitHub Login: @mikkelsen2000
* Microsoft Alias: **pemikkel**

**Comment by Mattp123** [comment] 2023-04-10 22:19
@mwebster5589 - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2023-04-10 22:19 UTC
Labels: alm, open-for-too-long, assigned-to-author, power-platform/svc, Pri2
