### ISSUE TITLE
Proxy not supported

### ISSUE THREAD

**Issue by andrew-sumner** [MicrosoftDocs/power-platform#625] opened 2021-03-05 03:19 UTC
I'm hoping I've reached the correct place, I'm trying to raise an issue for https://docs.microsoft.com/en-us/power-platform/alm/devops-build-tools

Our proxy is denying access for this task to download the power platform tool in our Azure DevOps Server pipeline.

For other tasks doing similar things I have set the HTTPS_PROXY variable to http://domain%5Cuser:password@proxy.company.co.nz, but this task either is not using this value and is using some other setting to determine which proxy to use, or it is stripping off the credentials component.

Either way we are unable to use it.

Any thoughts?

```
2021-03-05T02:25:43.7443173Z ##[section]Starting: Power Platform Tool Installer 
2021-03-05T02:25:43.8249066Z ==============================================================================
2021-03-05T02:25:43.8249509Z Task         : Power Platform Tool Installer
2021-03-05T02:25:43.8249816Z Description  : Power Platform Tool Installer
2021-03-05T02:25:43.8250066Z Version      : 0.0.17
2021-03-05T02:25:43.8250299Z Author       : Microsoft
2021-03-05T02:25:43.8250623Z Help         : [More Info](https://aka.ms/buildtoolsdoc)
2021-03-05T02:25:43.8250991Z ==============================================================================
2021-03-05T02:25:45.6750375Z Installing PS module Microsoft.PowerApps.Administration.PowerShell - 2.0.92 ...
2021-03-05T02:25:45.8202733Z Installing PS module Microsoft.Xrm.Tooling.PackageDeployment.Powershell - 3.3.0.898 ...
2021-03-05T02:25:45.8248858Z Installing PS module Microsoft.PowerApps.Checker.PowerShell - 1.0.28 ...
2021-03-05T02:25:49.3297195Z 
2021-03-05T02:25:49.3334783Z Name                           Version          Source           Summary       
2021-03-05T02:25:49.3474731Z ----                           -------          ------           -------       
2021-03-05T02:25:49.3493712Z nuget                          2.8.5.208        https://onege... NuGet provi...
2021-03-05T02:25:52.7258149Z ##[error]Source Location 'https://www.nuget.org/api/v2' is not valid.
2021-03-05T02:25:52.7470186Z Installing nuget pkg Microsoft.CrmSdk.CoreTools - 9.1.0.49 ...
2021-03-05T02:25:53.1927381Z ##[error]No match was found for the specified search criteria and package name 'Microsoft.CrmSdk.CoreTools'. Try Get-PackageSource to see all available registered package sources.
2021-03-05T02:25:53.2585547Z ##[section]Finishing: Power Platform Tool Installer 
```

**Comment by Mattp123** [comment] 2023-04-10 22:18
@andrew-sumner - Thanks for your feedback. We are closing this issue because we are either unable to find relevant information or reproduce this. If you're still experiencing the issue described here, please reopen or create a new issue.

**Closed by Mattp123** 2023-04-10 22:18 UTC
Labels: alm, open-for-too-long, Pri3
